### PR TITLE
fixing .Values.gitRepository.spec.ignore to support multiline strings

### LINKED ISSUE #133: flux-sync .gitRepository.spec.ignore multiline support
### Describe the bug a clear and concise description of what the bug is.

I'm struggling setting a multiline git ignore configuration like:

```yaml
gitRepository:
  spec:
    url: repository_url
    ref: {"branch": "branch"}
    ignore: |
      # exclude all
      /*
      # include deploy dir
      !/cluster-name/fluxcd-applications
```

This results in:

```
Error: YAML parse error on flux2-sync/templates/flux-gitrepository.yaml: error converting YAML to JSON: yaml: line 20: could not find expected ':'
```

### What's your helm version?

3.9.4

### What's your kubectl version?

v1.24.3

### What's the chart version?

1.0.0

### What happened?

_No response_

### What you expected to happen?

_No response_

### How to reproduce it?

_No response_

### Enter the changed values of values.yaml?

gitRepository:
  spec:
    ignore: |
      # exclude all
      /*
      # include deploy dir
      !/cluster-name/fluxcd-applications

### Enter the command that you execute and failing/misfunctioning.

helm upgrade -n flux-system -f x fluxcd-apps fluxcd-community/flux2-sync

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by odise**
Signed-off-by: Jan Nabbefeld <jan@odise.de>

#### Which issue this PR fixes
- fixes #133

#### Checklist

- [x] [DCO](https://github.com/fluxcd-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] helm-docs are updated
- [x] Helm chart is tested
- [ ] Update artifacthub.io/changes in Chart.yaml
- [x] Run `make reviewable`

### CODE REVIEW

**Comment by haarchri** [comment]
@odise thanks for adding this - can you update/add Testcase for this ? Thanks

**Comment by odise** [comment]
Will the absence of a test case holding you back from fixing this bug?

**Comment by dwerder** [comment]
The PR does not allow to add changes, otherwise I would quickly add the test.
Although the change information are not updated.
I will just merge that now and add a new PR with tests and the rest.

**Review by dwerder — APPROVED** [review]

**Comment by odise** [comment]
@dwerder awesome, thanks!

**Pull request merged**
