### PR TITLE
Add extra env support

### PR DESCRIPTION
**Pull request by madmatt112**
### What this PR does / why we need it:
Adds support for arbitrary environment variable injection into any of the controller deployments.

### Which issue this PR fixes
None.

### Special notes for your reviewer:
None.

### Checklist
- [X] [DCO](https://github.com/fluxcd-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [X] Chart Version bumped
- [X] helm-docs are updated
- [X] Helm chart is tested
- [X] Update artifacthub.io/changes in Chart.yaml
- [X] Run `make reviewable`

### CODE REVIEW

**Comment by dwerder** [comment]
Thanks for the PR.
I have a little problem with the fact, that it does more then the description says.

1. flux2-multi-tenancy chart is marked as deprecated. So we need no update there.
2. If the changelogs you added are not generated in some way, they will not be maintained. If we had such thing, it should be generated in a workflow step
3. It would be nice to add a check/unittest for the new variable

**Comment by madmatt112** [comment]
> 1. flux2-multi-tenancy chart is marked as deprecated. So we need no update there.
> 2. If the changelogs you added are not generated in some way, they will not be maintained. If we had such thing, it should be generated in a workflow step
> 3. It would be nice to add a check/unittest for the new variable

@dwerder, please see responses:
1. Will rollback the update as noted, thanks.
2. According to (https://github.com/fluxcd-community/helm-charts/blob/91b1d1d53b1c7ba0a6af92dfefd58137b152d7a9/CONTRIBUTING.md?plain=1#L29), running `helm-changelog` is specifically noted as a step in contributing to this repo. Should I remove this directive from the guidelines, and remove my changelog files?
3. I agree - I will include some form of check/test and update the PR.

**Comment by dwerder** [comment]
Thanks.
You are right. The step helm-changelog is outdated.

**Comment by k0da** [comment]
Any updates? We need this in order to set proxy settings for notification-controller.

**Comment by ravilr** [comment]
this has been addressed in https://github.com/fluxcd-community/helm-charts/pull/179

/close

**Pull request closed without merging**
