### PR TITLE
Flux v2.2.0: Update CRDs and component versions

### PR DESCRIPTION
**Pull request by rsafonseca**
#### What this PR does / why we need it:
Updates the CRDs to include the latest specs, updates components to latest versions

#### Special notes for your reviewer:
Allows the helm-chart to be used for proper install/function of the latest component versions

#### Checklist

- [x] [DCO](https://github.com/fluxcd-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] helm-docs are updated
- [x] Helm chart is tested
- [x] Update artifacthub.io/changes in Chart.yaml
- [x] Run `make reviewable`

### CODE REVIEW

**Comment by rsafonseca** [comment]
Yeah, i was about to ask about bumping those since the release date is expected to be today right? :)

**Comment by stefanprodan** [comment]
Yeap couple of hours from now

**Comment by stefanprodan** [comment]
@rsafonseca please bump the app version and the CLI tag, we've released v2.2.0

**Comment by rsafonseca** [comment]
all set @stefanprodan 👍

**Comment by stefanprodan** [comment]
Please bump the other charts as well

**Comment by rsafonseca** [comment]
Done, it was actually in 2 places :)

**Comment by rsafonseca** [comment]
argh, the liniting job is tying all the charts together so it's failing for the charts i didn't update :(

**Comment by stefanprodan** [comment]
Please bump the chart version for flux2-notification and flux2-sync

**Comment by stefanprodan** [comment]
> argh, the liniting job is tying all the charts together so it's failing for the charts i didn't update :(

There is an update, the app version so chart version needs a bump too

**Comment by rsafonseca** [comment]
Yeah, just noticed that as I typed it... the Makefile target did that for me hehe.. i added the notification.toolkit.fluxcd.io apiversion bump to flux2-notification chart as a bonus :)

**Comment by rsafonseca** [comment]
It should be all green now :)

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @rsafonseca 🏅

**Pull request merged**
