### PR TITLE
only trigger chart linting if charts change

### PR DESCRIPTION
**Pull request by dwerder**
#### What this PR does / why we need it:

only trigger chart linting if charts change

#### Checklist

- [ ] [DCO](https://github.com/fluxcd-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] helm-docs are updated
- [ ] Helm chart is tested

### CODE REVIEW

**Comment by pierluigilenoci** [comment]
@dwerder ?

**Comment by dwerder** [comment]
@pierluigilenoci ?

**Comment by pierluigilenoci** [comment]
I was curious to understand what had happened this PR.

**Comment by pierluigilenoci** [comment]
Now another question comes to me.
Why close one PR to open another with almost the same changes? 😆

**Comment by dwerder** [comment]
Because this PRs were opened nearly at the same time. And the one by Stefan fixed more stuff.

**Pull request closed without merging**
