### PR TITLE
Fix targetPath pattern

### LINKED ISSUE #129: HelmRelease valuesFrom broken for dotted annotations
### Describe the bug a clear and concise description of what the bug is.

See this issue: https://github.com/fluxcd/helm-controller/issues/542

The problem is that the CRD is not up2date:
See
https://github.com/fluxcd-community/helm-charts/blame/main/charts/flux2/templates/helm-controller.crds.yaml#L723
vs
https://github.com/fluxcd/helm-controller/blame/main/config/crd/bases/helm.toolkit.fluxcd.io_helmreleases.yaml#L708

### What's your helm version?

v3.9.4

### What's your kubectl version?

v3.9.4

### What's the chart version?

1.6.0

### What happened?

_No response_

### What you expected to happen?

_No response_

### How to reproduce it?

_No response_

### Enter the changed values of values.yaml?

_No response_

### Enter the command that you execute and failing/misfunctioning.

N/A

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by as42sl**
#### Which issue this PR fixes
* fixes #129

### CODE REVIEW

**Comment by stefanprodan** [comment]
Given that the chart doesn't have the upstream CRDs released months ago, I think many other changes are left out... We need to have some test so this never happens again, who knows how many changes are omitted from the chart.

**Comment by haarchri** [comment]
@stefanprodan Looks Like the CRDs updated Last with: https://github.com/fluxcd-community/helm-charts/commit/49e4ae4d166cedd4e963d8168fd570b76d6a8eb5

**Comment by stefanprodan** [comment]
@haarchri is there a bug in the script that updates the CRDs then?

**Comment by haarchri** [comment]
Yeah i will check at the moment what happend

**Comment by haarchri** [comment]
i found the bug and will open a PR shortly

**Comment by haarchri** [comment]
@as42sl  thanks for bring up the issue 
please check: https://github.com/fluxcd-community/helm-charts/pull/132
if fixed the generator

**Pull request closed without merging**
