### PR TITLE
fix crds for 0.24.0 release

### PR DESCRIPTION
**Pull request by haarchri**
Signed-off-by: haarchri <chhaar30@googlemail.com>

#### What this PR does / why we need it:
upgrade CRDS for 0.24.0 release

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - followup for https://github.com/fluxcd-community/helm-charts/pull/29

#### Checklist

- [x] [DCO](https://github.com/fluxcd-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] helm-docs are updated
- [x] Helm chart is tested

### CODE REVIEW

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @haarchri

I think we need to document the procedure for updating Flux, almost all minor releases come with changes to some API (CRDs, controller flags, etc). How ca we make sure the chart is in sync?

**Comment by haarchri** [comment]
can we only extract the CRDs from flux via cli ? then it is easy with check-diff and run a generate step

**Comment by stefanprodan** [comment]
You can build this overlay https://github.com/fluxcd/flux2/blob/main/manifests/crds/kustomization.yaml, it will give you all CRDs.

**Comment by haarchri** [comment]
thanks - i will comeback with a automatic solution - thanks

**Pull request merged**
