### PR TITLE
Rename kustomization.yaml generated by flux2-sync 

### PR DESCRIPTION
**Pull request by suryapandian**
#### What this PR does / why we need it:
Renames `kustomization.yaml` to `flux-kustomization.yaml`
and `gitrepository.yaml` to `flux-gitrepository.yaml`

We need this fix because `kustomization.yaml` by convention of kustomize refers to [this](https://kubectl.docs.kubernetes.io/references/kustomize/glossary/#kustomization).

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes https://github.com/fluxcd-community/helm-charts/issues/105

#### Checklist

- [x] [DCO](https://github.com/fluxcd-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] helm-docs are updated
- [x] Helm chart is tested
- [ ] Update artifacthub.io/changes in Chart.yaml
- [x] Run `make reviewable`

### CODE REVIEW

**Comment by suryapandian** [comment]
`charts/flux2-sync/README.md` got automatically updated when I ran  `helm-docs`

**Comment by haarchri** [comment]
Can you Check DCO ? Then we can run E2E Checks

**Comment by suryapandian** [comment]
> Can you Check DCO ? Then we can run E2E Checks

Done ✅

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @suryapandian 🏅

**Pull request merged**
