### PR TITLE
Add uninstall to e2e test suite

### PR DESCRIPTION
**Pull request by stefanprodan**
#### Checklist

- [x] [DCO](https://github.com/fluxcd-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] helm-docs are updated
- [x] Helm chart is tested

### CODE REVIEW

**Comment by stefanprodan** [comment]
No idea why the lint job no longer creates a kind cluster....

**Comment by dwerder** [comment]
The problem is, that we check if there were changes in the chart and only then we start a kind cluster and the tests. The condition check is missing on the chart linting test. Thats why it is triggered, even so kind is not started.

Fix is to add the following line
https://github.com/fluxcd-community/helm-charts/blob/main/.github/workflows/lint-test.yaml#L41
`if: steps.list-changed.outputs.changed == 'true'`

**Comment by stefanprodan** [comment]
@dwerder I really doubt Helm knows to properly uninstall Flux, it works because Helm doesn't check for CRD deletion, but CRDs are stuck on the cluster forever blocking namespaces and everything else. The only way to uninstall Flux without breaking your whole cluster is by suspending first all Flux custom resources, then by patching them to remove finalizers.

**Comment by stefanprodan** [comment]
I guess we could fix this by having an uninstall hook that calls `flux uninstall --keep-namespace`.

**Review by haarchri — APPROVED** [review]

**Pull request merged**
