### PR TITLE
build: update release to push to ghcr

### PR DESCRIPTION
**Pull request by dmccaffery**
Signed-off-by: Deavon M. McCaffery <dmccaffery@users.noreply.github.com>

#### What this PR does / why we need it:

Update the release pipeline to publish helm charts to ghcr in addition to GitHub releases.

#### Which issue this PR fixes

Closes: #91 

#### Checklist
- [x] [DCO](https://github.com/fluxcd-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed

### CODE REVIEW

**Comment by stefanprodan** [comment]
@dmccaffery yes please bump the versions so we can make the repos public afterwords and test them.

**Comment by dmccaffery** [comment]
@stefanprodan finally got a chance to do this -- ready for review so we can test

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @dmccaffery 🏅

**Comment by stefanprodan** [comment]
@dmccaffery I made all repos public

**Comment by dmccaffery** [comment]
@stefanprodan tested via oci, so it all works!

image

**Pull request merged**
