### PR TITLE
feat(chart): added basic flux2-multi-tenancy chart

### PR DESCRIPTION
**Pull request by haarchri**
Signed-off-by: haarchri <chhaar30@googlemail.com>

#### What this PR does / why we need it:
- added flux2-multi-tenant based on https://github.com/fluxcd/flux2-multi-tenancy
- fixed .gitignore for ex. dependencies

#### Checklist

- [x] [DCO](https://github.com/fluxcd-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [x] helm-docs are updated
- [x] Helm chart is tested

### CODE REVIEW

**Review by dwerder — APPROVED** [review]

**Comment by stefanprodan** [comment]
Hmm this name is super confusing, what will happen to this chart when we'll implement: https://github.com/fluxcd/flux2/pull/2093 ?

**Comment by dwerder** [comment]
It was named so, because it is the implementation of https://github.com/fluxcd/flux2-multi-tenancy
So the name seem to be legit.

**Comment by dwerder** [comment]
Should we rename it to `flux2-multi-tenancy-kyverno` ?

**Comment by stefanprodan** [comment]
Are we going to delete this chart once RFC-0003 gets in? The flux2-multi-tenancy will use the new bootstrap option.

**Comment by dwerder** [comment]
Then we can adjust it (and have a major version bump) or delete it, If it gets totally obsolet.

**Comment by stefanprodan** [comment]
Cool 👍

**Pull request merged**
