### PR TITLE
Update Flux to v2.0.0-rc.1

### PR DESCRIPTION
**Pull request by suryapandian**
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #

#### Checklist

- [ ] [DCO](https://github.com/fluxcd-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [ ] Chart Version bumped
- [ ] helm-docs are updated
- [ ] Helm chart is tested
- [ ] Update artifacthub.io/changes in Chart.yaml
- [ ] Run `make reviewable`

### CODE REVIEW

**Comment by stefanprodan** [comment]
Hey @suryapandian updating the charts must be done using the Makefile, please see https://github.com/fluxcd-community/helm-charts/pull/170

**Comment by suryapandian** [comment]
> Hey @suryapandian updating the charts must be done using the Makefile, please see #170

thank you trying it [here](https://github.com/fluxcd-community/helm-charts/pull/174)

**Comment by stefanprodan** [comment]
@suryapandian instead of opening PRs, please test this locally, once you get Flux 2.0 RC.1 running OK from the local charts, push those changes in this PR.

**Comment by suryapandian** [comment]
> @suryapandian instead of opening PRs, please test this locally, once you get Flux 2.0 RC.1 running OK on your cluster from the local charts, push those changes in this PR.

ya makes sense to stop spamming, closed the PRs, many test cases were failing and I don't have much leads either 🙈

**Pull request closed without merging**
