### PR TITLE
feat(flux2): add webhook-receiver ingress

### LINKED ISSUE #128: Add ingress objects for notification controller
### Is your feature request related to a problem ?

Notification controller [receivers](https://fluxcd.io/flux/components/notification/receiver/) allow forges like github or gitlab to send events when the repository state changes, allowing to reduce latency without unreasonable polling frequencies.

For the notification controller to be reachable, most clusters will require an ingress object in addition to the service (especially since it is hardcoded to `ClusterIP`).

### Describe the solution you'd like.

I believe it will be great if the flux2 helm chart allowed to configure an ingress object from `values.yaml`. This object would be disabled by default to prevent accidental exposure of the notification controller.

### Describe alternatives you've considered.

Adding the ingress object separately from the helm chart is something possible, but causes friction as in order to locate the service from the ingress object, you need to know labels and release names that are defined inside the chart. Having to duplicate these to a separate point makes easy to accidentally misconfigure the ingress object.

### Additional context.

If this is a feature you want to add, please LMK. I have some experience working with charts and I'm open to implement it here.

### PR DESCRIPTION
**Pull request by sebastiangaiser**
#### What this PR does / why we need it:
Ingress resource for notificationController's receiver webhook service

Used values for testing:
```
notificationController:
  webhookReceiver:
    ingress:
      create: true
      ingressClassName: nginx
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
      hosts:
        - host: flux-webhook.example.com
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: flux-webhook-tls
          hosts:
            - flux-webhook.example.com
```

#### Which issue this PR fixes
  - fixes #128 
  - superseds #163
  - superseds #169

#### Checklist

- [x] [DCO](https://github.com/fluxcd-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] helm-docs are updated
- [x] Helm chart is tested
- [x] Update artifacthub.io/changes in Chart.yaml
- [x] Run `make reviewable`

### CODE REVIEW

**Comment by sebastiangaiser** [comment]
[This](https://github.com/helm/chart-testing-action/issues/132) seams to be related. Shall I bump the version, too?

**Comment by stefanprodan** [comment]
Yes please bump the version

**Comment by stefanprodan** [comment]
You need to bump the patch version of all charts due to the readme change.

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @sebastiangaiser 🥇

**Pull request merged**
