### PR TITLE
flux2-notification: fix provider template

### PR DESCRIPTION
**Pull request by yurymuski**
#### Which issue this PR fixes

fix: #178

#### Checklist
- [x] [DCO](https://github.com/fluxcd-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] helm-docs are updated
- [x] Helm chart is tested
- [x] Update artifacthub.io/changes in Chart.yaml
- [x] Run `make reviewable`

### CODE REVIEW

**Comment by yurymuski** [comment]
seems you are using old version of helm-unit tests, new one does not know about `--helm3` flag, and requires indentation changes

pushed commit w/o indentation changes

**Comment by stefanprodan** [comment]
@yurymuski could you please update helm-test in a different PR?

**Review by stefanprodan — APPROVED** [review]
LGTM 

Thanks @yurymuski 🏅

**Comment by yurymuski** [comment]
@stefanprodan sure, I can update tests, will add it todo list :)

**Pull request merged**
