### PR TITLE
fix(flux2): add variable to customise cluster domain (#139)

### LINKED ISSUE #139: bug: we should not assume that the cluster domain is cluster.local
https://github.com/fluxcd-community/helm-charts/blob/b3761bafd79cf1efb2b275309a42cb335abcc614/charts/flux2/templates/source-controller.yaml#L47

In our environments, we do not use the default cluster domain of cluster.local -- this either needs to be a variable, or allow resolv search domains to be used by dropping the domain.

### PR DESCRIPTION
**Pull request by dmccaffery**
* add new `clusterDomain` variable which defaults to `cluster.local`
* use `clusterDomain` for source-controller `storage-adv-addr` argument
* use `clusterDomain` for `events-addr` argument

NOTES:

The source-controller manifest included a hard-coded advertising address with `cluster.local`. In some environments, the cluster domain is modified, which broke the kustomize controller from being able to resolve the source controller to acquire artifacts.

BREAKING CHANGE:

The `eventsaddr` variable has been removed as it is no longer necessary. The new `clusterDomain` variable is now used to create a fully-qualified addresses throughout the deployment manifiests.

Signed-off-by: Deavon M. McCaffery <dmccaffery@users.noreply.github.com>

#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*
  - fixes #139 

#### Checklist

- [X] [DCO](https://github.com/fluxcd-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [X] Chart Version bumped
- [X] helm-docs are updated
- [X] Helm chart is tested
- [X] Update artifacthub.io/changes in Chart.yaml
- [X] Run `make reviewable`

### CODE REVIEW

**Comment by stefanprodan** [comment]
If we are making breaking changes I would suggest correcting the variables names, some of them are not capitalized correctly for example `serviceaccount` should be `serviceAccount`, `additionalargs` should be `additionalArgs`, `watchallnamespaces` should be `watchAllNamespaces`.

**Comment by dmccaffery** [comment]
I agree. It drives me nuts. 🙃

**Comment by dmccaffery** [comment]
@stefanprodan I fixed the casing of everything that I could find. I've left them each in separate commits to make them easier to review. Per the contributing guide, changes should be squashed before opening a PR, but I figured that would make this much more difficult to review.

**Review by stefanprodan — APPROVED** [review]
LGTM 

Thanks @dmccaffery 🥇

**Pull request merged**
