### PR TITLE
chore(update) update to AppVersion 0.36.0

### PR DESCRIPTION
**Pull request by julienduchesne**
Closes https://github.com/fluxcd-community/helm-charts/issues/136

Signed-off-by: Julien Duchesne <julien.duchesne@grafana.com>

#### Checklist

- [x] [DCO](https://github.com/fluxcd-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] helm-docs are updated
- [x] Helm chart is tested
- [x] Update artifacthub.io/changes in Chart.yaml
- [x] Run `make reviewable`

### CODE REVIEW

**Comment by julienduchesne** [comment]
Looks like the helm version that was installed by CI is v3.0.0.alpha.1 and it's breaking: https://github.com/fluxcd-community/helm-charts/actions/runs/3345291198/jobs/5540632851

**Comment by julienduchesne** [comment]
The fix for the Helm CI failure is here: https://github.com/fluxcd-community/helm-charts/pull/138

**Comment by stefanprodan** [comment]
Hey @julienduchesne can you please rebase. Thanks

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @julienduchesne 🥇

**Pull request merged**
