### PR TITLE
chore: upgrade charts to Flux v2.0.0 (GA) 

### PR DESCRIPTION
**Pull request by jimid27**
#### What this PR does / why we need it:
- Upgrades the helm charts to use the GA Flux V2 release
#### Which issue this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*

#### Checklist

- [x] [DCO](https://github.com/fluxcd-community/helm-charts/blob/main/CONTRIBUTING.md#sign-off-your-work) signed
- [x] Chart Version bumped
- [x] helm-docs are updated
- [x] Helm chart is tested
- [x] Update artifacthub.io/changes in Chart.yaml
- [x] Run `make reviewable`

### CODE REVIEW

**Comment by stefanprodan** [comment]
```
Kubernetes version v1.21.1 does not match >=1.24.0-0
```

We need to bump Kubernetes in e2e tests to `kindest/node:v1.24.15`. Can you please do that in 
- https://github.com/fluxcd-community/helm-charts/blob/main/.github/workflows/e2e-sync.yaml#L21
- https://github.com/fluxcd-community/helm-charts/blob/main/.github/workflows/lint-test.yaml#L45

**Comment by jimid27** [comment]
> with:
>           cluster_name: kind
>           node_image: kindest/node:v1.24.15

Per the [README](https://github.com/engineerd/setup-kind#engineerdsetup-kind) I believe we want to use `image` vs `node_image` for this run, right?

**Comment by jimid27** [comment]
Something else seems weird with the e2e sync 🤔 as we are creating a cluster named `kind` using k8s version `1.24.5` and yet it is still failing (https://github.com/fluxcd-community/helm-charts/actions/runs/5466764719/jobs/9952168866?pr=177#step:4:13)

**Comment by stefanprodan** [comment]
@jimid27 we need to replace the `engineerd/setup-kind@v0.5.0` which is deprecated with  `helm/kind-action@v1.4.0` like so:

```
      - name: Setup Kubernetes
        uses: helm/kind-action@v1.4.0
        with:
          cluster_name: kind
          node_image: kindest/node:v1.24.15
```

**Comment by jimid27** [comment]
> @jimid27 we need to replace the `engineerd/setup-kind@v0.5.0` which is deprecated with `helm/kind-action@v1.4.0` like so:
> 
> ```
>       - name: Setup Kubernetes
>         uses: helm/kind-action@v1.4.0
>         with:
>           cluster_name: kind
>           node_image: kindest/node:v1.24.15
> ```
omg my bad I misread your previous post. Change incoming

**Comment by stefanprodan** [comment]
Works now GG! can you please squash the last 4 commits.

**Comment by jimid27** [comment]
> Works now GG! can you please squash the last 4 commits.

should be squashed lmk if theres anything else needed here (or if I messed the squash up 😄 )

**Comment by stefanprodan** [comment]
Eh the squash didn't work, I can do it at merge time into a single commit.

**Pull request merged**
